
server:
  servlet:
    contextPath: /devops-app
  port: 8484
spring:
    application:
      name: devops-app
    datasource:
      url: jdbc:postgresql://localhost:5432/employeedb
      username: postgres
      password: admin
devops_app:
      base_url: /v1
      employee: /employee
      base_uri: localhost:8484

